# frozen_string_literal: true

source "https://rubygems.org"

gem "bootsnap", "1.13.0", require: false
gem "bootstrap-sass", "3.4.1"
gem "bunny", "2.19.0"
gem "coffee-rails", "5.0.0"
gem "declarative-option", "0.1.0"
gem "devise", "4.8.1"
gem "devise-guests", "0.8.1"
gem "down", "~> 5.0"
gem "ezid-client", "1.9.1"
gem "fog-aws", "3.14.0"
gem "hyrax",
  git: "https://github.com/samvera/hyrax.git",
  branch: "3.x-stable"
gem "jbuilder", "2.11.5"
gem "jquery-rails", "4.5.0"
gem "okcomputer", "1.18.4"
gem "omniauth-google-oauth2", "0.8.2"
gem "pg", "1.4.3"
gem "puma", "5.6.4"
gem "rails", "5.2.8.1"
gem "redis", "4.7.1"
gem "rsolr", "2.5.0"
gem "sass-rails", "5.1.0"
gem "sidekiq", "6.5.6"
gem "surfliner_schema", path: "../gems/surfliner_schema"
gem "tinymce-rails", "5.10.5"
gem "turbolinks", "5.2.1"
gem "uglifier", "4.2.0"
gem "valkyrie-sequel", "~> 2.2.0"
gem "valkyrie-shrine", "~> 1.0"

group :development do
  gem "listen", ">= 3.0.5", "< 3.7.2"
end

group :development, :test do
  gem "byebug", "11.1.3"
  gem "capybara", "3.37.1"
  gem "capybara-screenshot", "1.0.26"
  gem "database_cleaner-active_record", "2.0.1"
  gem "equivalent-xml", "~> 0.6.0"
  gem "pry-byebug", "3.10.0"
  gem "pry-doc", "1.3.0"
  gem "pry-rails", "0.3.9"
  gem "pry-rescue", "1.5.2"
  gem "rspec_junit_formatter", "0.5.1"
  gem "rspec-rails", "5.1.2"
  gem "scss_lint", "0.59.0", require: false
  gem "scss_lint_reporter_checkstyle", "0.2.0", require: false
  gem "selenium-webdriver", "4.3.0"
  gem "standard", "1.16.0"
end
