# frozen_string_literal: true

source "https://rubygems.org"

gem "bootsnap", "1.16.0", require: false
gem "bootstrap", "4.6.2"
gem "bulkrax",
  git: "https://github.com/samvera-labs/bulkrax.git",
  branch: "hyrax-4-rails-6"
gem "bunny", "2.20.3"
gem "coffee-rails", "5.0.0"
gem "declarative-option", "0.1.0"
gem "devise", "4.9.2"
gem "devise-guests", "0.8.1"
gem "down", "~> 5.0"
gem "ezid-client", "1.9.4"
gem "fog-aws", "3.18.0"
gem "hyrax", "4.0.0"
gem "jbuilder", "2.11.5"
gem "jquery-rails", "4.5.1"
gem "okcomputer", "1.18.4"
gem "omniauth-google-oauth2", "0.8.2"
gem "pg", "1.5.3"
gem "puma", "6.3.0"
gem "rails", "6.1.7.3"
gem "rdf-edtf",
  git: "https://gitlab.com/surfliner/rdf-edtf.git",
  branch: "trunk"
gem "redis", "4.8.1"
gem "rsolr", "2.5.0"
gem "sass-rails"
gem "sidekiq", "7.1.1"
gem "surfliner_schema", path: "../gems/surfliner_schema"
gem "tinymce-rails", "5.10.7"
gem "turbolinks", "5.2.1"
gem "twitter-typeahead-rails"
gem "uglifier", "4.2.0"
gem "valkyrie-sequel", "~> 3.0"
gem "valkyrie-shrine", "~> 1.0"

group :development do
  gem "listen", ">= 3.0.5", "< 3.8.1"
end

group :development, :test do
  gem "byebug", "11.1.3"
  gem "capybara", "3.39.1"
  gem "capybara-screenshot", "1.0.26"
  gem "database_cleaner-active_record", "2.1.0"
  gem "equivalent-xml", "~> 0.6.0"
  gem "factory_bot_rails", "6.2.0"
  gem "pry-byebug", "3.10.1"
  gem "pry-doc", "1.4.0"
  gem "pry-rails", "0.3.9"
  gem "pry-rescue", "1.5.2"
  gem "rspec_junit_formatter", "0.6.0"
  gem "rspec-rails", "5.1.2"
  gem "scss_lint", "0.60.0", require: false
  gem "scss_lint_reporter_checkstyle", "0.2.0", require: false
  gem "selenium-webdriver", "4.9.0"
  gem "standard", "1.28.3"
end
