# frozen_string_literal: true

ruby '2.6.2'

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'capybara_discoball', '~> 0.1.0', group: 'test'
gem 'dotenv',             group: %w[development test]
gem 'dry-configurable',   '~> 0.8.1'
gem 'dry-events',         '~> 0.1.0'
gem 'dry-system',         '~> 0.9.2'
gem 'dry-transaction',    '~> 0.13.0'
gem 'factory_bot',        group: 'test'
gem 'pry',                group: %w[development test]
gem 'rack-healthcheck',   '~> 0.2.0'
gem 'rack-test',          group: 'test'
gem 'racksh'
gem 'rsolr',              '~> 2.2.1'
gem 'rspec',              group: 'test'
gem 'rubocop',            group: %w[development test]
gem 'rubocop-rspec',      group: %w[development test]
gem 'shotgun',            group: 'development'
gem 'sinatra',            '~> 2.0.5'
gem 'timecop',            group: 'test'
gem 'valkyrie-sequel',    '~> 1.0.0'
