source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem "bootsnap", "1.13.0", require: false
gem "debug", "1.6.2", platforms: %i[mri mingw x64_mingw], group: %(development test)
gem "oai", "1.2.1"
gem "okcomputer", "1.18.4"
gem "pg", "1.4.3"
gem "puma", "5.6.4"
gem "rails", "7.0.2"
gem "rspec-rails", "5.1.2", group: "test"
gem "rspec_junit_formatter", "0.5.1", group: "test"
gem "standard", "1.16.0", group: %(development test)
gem "sequel", "5.59.0", group: %(development test)
gem "tzinfo-data", "2.0.4", platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  gem "database_cleaner-active_record", "2.0.1"
end
