source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.2'

gem 'rails', '~> 5.2.3'
gem 'blacklight', '~> 7.0'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'bootstrap', '~> 4.0'
gem 'byebug', group: %(development test), platforms: [:mri, :mingw, :x64_mingw]
gem 'devise', '~> 4.6'
gem 'devise-guests', '~> 0.6'
gem 'geoblacklight', '~> 2.0'
gem 'jbuilder', '~> 2.5'
gem 'jquery-rails', '~> 4.3'
gem 'listen', '>= 3.0.5', '< 3.2', group: :development
gem 'popper_js', '~> 1.14'
gem 'pry-rails', '~> 0.3', group: %(development, test)
gem 'puma', '~> 3.11'
gem 'rsolr', '>= 1.0', '< 3'
gem 'sass-rails', '~> 5.0'
gem 'spring', group: :development
gem 'spring-watcher-listen', '~> 2.0.0', group: :development
gem 'sqlite3', '~> 1.3.6'
gem 'turbolinks', '~> 5.2'
gem 'twitter-typeahead-rails', '0.11.1.pre.corejavascript'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'uglifier', '>= 1.3.0'
gem 'web-console', '>= 3.3.0', group: :development
gem 'webpacker', '~> 4.0'
