# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~> 2.6'

gem 'blacklight',              '~> 7.6.0'
gem 'bootsnap',                '>= 1.1.0', require: false
gem 'bootstrap',               '~> 4.3'
gem 'capybara',                group: 'test'
gem 'devise',                  '~> 4.6'
gem 'devise-guests',           '~> 0.6'
gem 'factory_bot_rails',       group: 'test'
gem 'geoblacklight',           '~> 2.3.0'
gem 'geoserver-publish',       '~> 0.2.1'
gem 'jbuilder',                '~> 2.5'
gem 'jquery-rails',            '~> 4.3'
gem 'nokogiri',                '~> 1.10.9'
gem 'okcomputer',              '~> 1.18'
gem 'optimist'
gem 'pg',                      '~> 1.1.4'
gem 'popper_js',               '~> 1.14'
gem 'puma',                    '~> 4.0'
gem 'rails',                   '~> 5.2.4'
gem 'rsolr',                   '>= 1.0', '< 3'
gem 'sass-rails',              '~> 6.0'
gem 'turbolinks',              '~> 5.2'
gem 'twitter-typeahead-rails', '0.11.1'
gem 'tzinfo-data',             '~> 1.2020.0'
gem 'uglifier',                '>= 1.3.0'

group :development do
  gem 'letter_opener_web'
  gem 'web-console'
end

group :development, :test do
  gem 'byebug',                  platforms: %i[mri mingw x64_mingw]
  gem 'dotenv-rails',            '~> 2.7'
  gem 'pry-rails',               '~> 0.3'
  gem 'rubocop'
  gem 'rubocop-rails'
  gem 'rubocop-rspec'
  gem 'solr_wrapper'
end

group :test do
  gem 'rspec-its'
  gem 'rspec_junit_formatter'
  gem 'rspec-rails', '~> 4.0'
end
