# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem "blacklight", "7.31.0"
gem "bootsnap", ">= 1.1.0", require: false
gem "bootstrap", "~> 4.3"
gem "bunny", "2.20.3"
gem "byebug", platforms: %i[mri mingw x64_mingw], group: %i[development test]
gem "capybara", group: [:test]
gem "devise", "~> 4.6"
gem "devise-guests", "~> 0.6"
gem "dotenv-rails", "~> 2.7", group: %i[development test]
gem "factory_bot_rails", group: [:test]
gem "fog-aws", "3.18.0"
gem "geoblacklight", "4.0.0"
gem "geoserver-publish", "0.6.0"
gem "jbuilder", "~> 2.5"
gem "jquery-rails", "~> 4.3"
gem "json_schemer", "0.2.24"
gem "letter_opener_web"
gem "listen", "3.8.0"
gem "mimemagic", "0.4.3"
gem "nokogiri", "~> 1.14.0"
gem "okcomputer", "~> 1.18"
gem "optimist"
gem "pg", "~> 1.4.0"
gem "pry-rails", "~> 0.3", group: %i[development test]
gem "puma", "5.6.5"
gem "rails", "7.0.4.3"
gem "rsolr", ">= 1.0", "< 3"
gem "rspec-its", group: [:test]
gem "rspec-rails", "~> 5.0", group: [:test]
gem "rspec_junit_formatter", group: [:test]
gem "sass-rails", "~> 6.0"
gem "standard", "1.27.0"
gem "turbolinks", "~> 5.2"
gem "twitter-typeahead-rails", "0.11.1"
gem "tzinfo-data", "~> 1.2023.0"
gem "uglifier", ">= 1.3.0"
gem "view_component", "< 2.82.1"
gem "web-console", group: [:development]
