source "https://rubygems.org"

gem "bootsnap", "1.16.0", require: false
gem "debug", "1.8.0", platforms: %i[mri mingw x64_mingw], group: %(development test)
gem "hyrax-acl",
  git: "https://github.com/samvera-labs/hyrax-acl.git"
gem "okcomputer", "1.18.4"
gem "pg", "1.5.4"
gem "puma", "6.3.1"
gem "rack-test", group: "test"
gem "rails", "7.0.8"
gem "rdf-edtf",
  git: "https://gitlab.com/surfliner/rdf-edtf.git",
  branch: "trunk"
gem "rspec_junit_formatter", "0.6.0", group: "test"
gem "rspec-rails", "6.0.1", group: "test"
gem "standard", "1.28.3", group: %(development test)
gem "surfliner_schema", path: "../gems/surfliner_schema"
gem "tzinfo-data", "2.0.4", platforms: %i[mingw mswin x64_mingw jruby]
gem "valkyrie", "3.0.3"
gem "valkyrie-sequel", "3.0.0"
