source "https://rubygems.org"

gem "bootsnap", "1.10.2", require: false
gem "debug", "1.4.0", platforms: %i[mri mingw x64_mingw], group: %(development test)
gem "puma", "5.6.1"
gem "rack-test", group: "test"
gem "rails", "7.0.1"
gem "rspec-rails", "5.1.0", group: "test"
gem "rspec_junit_formatter", "0.5.1", group: "test"
gem "standard", "1.7.0", group: %(development test)
gem "tzinfo-data", "2.0.4", platforms: %i[mingw mswin x64_mingw jruby]
gem "valkyrie", "2.2.0"
