source "https://rubygems.org"

gem "bootsnap", "1.12.0", require: false
gem "debug", "1.6.1", platforms: %i[mri mingw x64_mingw], group: %(development test)
gem "okcomputer", "1.18.4"
gem "pg", "1.4.1"
gem "puma", "5.6.4"
gem "rack-test", group: "test"
gem "rails", "7.0.1"
gem "rspec_junit_formatter", "0.5.1", group: "test"
gem "rspec-rails", "5.1.2", group: "test"
gem "standard", "1.13.0", group: %(development test)
gem "surfliner_schema", path: "../gems/surfliner_schema"
gem "tzinfo-data", "2.0.4", platforms: %i[mingw mswin x64_mingw jruby]
gem "valkyrie", "2.2.0"
gem "valkyrie-sequel", "~> 2.2.0"
