source 'https://rubygems.org'

gem 'blacklight', ' ~> 6.0'
gem 'blacklight-gallery', '>= 0.3.0'
gem 'blacklight-oembed', '>= 0.1.0'
gem 'blacklight-spotlight', github: 'projectblacklight/spotlight'
gem 'devise'
gem 'devise-guests', '~> 0.6'
gem 'devise_invitable'
gem 'friendly_id'
gem 'jquery-rails'
gem 'puma'
gem 'rails', '~> 5.1.6'
gem 'riiif'
gem 'rsolr', '>= 1.0'
gem 'sass-rails'
gem 'sitemap_generator'
gem 'sqlite3'
gem 'trollop'
gem 'uglifier', '>= 1.3.0'

group :development, :test do
  gem 'byebug'
  gem 'capistrano-rails'
  gem 'capybara'
  gem 'method_source'
  gem 'pry'
  gem 'pry-doc'
  gem 'selenium-webdriver'
  gem 'solr_wrapper', '>= 0.3'
end
