# frozen_string_literal: true

source "https://rubygems.org"

gem "activerecord-nulldb-adapter"
gem "blacklight", "7.18.1"
gem "blacklight-gallery", "3.3.1"
gem "blacklight-oembed", "1.1.0"
gem "blacklight-spotlight",
    git: "https://gitlab.com/surfliner/spotlight.git",
    branch: "trunk"
gem "bootsnap", "1.12.0", require: false
gem "bootstrap", "4.6.1"
gem "cancancan",
    git: "https://github.com/CanCanCommunity/cancancan.git",
    ref: "be14fdae4d14cff0a92c719b39889571093d82a5"
gem "carrierwave-aws", "1.5.0"
gem "dalli", "2.7.11"
gem "devise", "4.8.1"
gem "devise-guests", "0.8.1"
gem "friendly_id", "5.4.2"
gem "jquery-rails", "4.5.0"
gem "letter_opener_web", "2.0.0"
gem "mimemagic", "0.4.3"
gem "okcomputer", "1.18.4"
gem "omniauth", "2.1.0"
gem "omniauth-google-oauth2", "1.0.1"
gem "optimist", "3.0.1"
gem "pg", "1.4.1"
gem "puma", "5.6.4"
gem "rails", "6.1.6.1"
gem "riiif", git: "https://github.com/curationexperts/riiif.git"
gem "rsolr", "2.5.0"
gem "sass-rails", "6.0.0"
gem "sidekiq", "6.5.1"
gem "sitemap_generator", "6.2.1"
gem "uglifier", "4.2.0"
gem "view_component", "2.35.0" # TODO: figure out what's breaking between here and 2.55.0

group :development, :test do
  gem "byebug", "11.1.3"
  gem "capybara", "3.37.1"
  gem "capybara-screenshot", "1.0.26"
  gem "database_cleaner-active_record", "2.0.1"
  gem "dotenv-rails", "2.7.6"
  gem "factory_bot_rails", "6.2.0"
  gem "method_source", "1.0.0"
  gem "pry-byebug", "3.9.0"
  gem "pry-doc", "1.3.0"
  gem "pry-rails", "0.3.9"
  gem "pry-rescue", "1.5.2"
  gem "rspec_junit_formatter", "0.5.1"
  gem "rspec-rails", "5.1.2"
  gem "scss_lint", "0.59.0", require: false
  gem "scss_lint_reporter_checkstyle", "0.2.0", require: false
  gem "selenium-webdriver", "4.1.0"
  gem "shoulda-matchers", "5.1.0"
  gem "standard", "1.13.0"
  gem "webmock", "3.14.0"
end
